=== Letractively/sj-http-server/etc/xsd/sj-http-server.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           xmlns:tns="http://sj-http-server.googlecode.com/server"
           targetNamespace="http://sj-http-server.googlecode.com/server"
           elementFormDefault="qualified">

<xs:element name="server-conf">
  <xs:complexType>
    <xs:sequence>
      <xs:element name="listen-interface" type="xs:string"/>
      <xs:element name="listen-port" type="xs:integer"/>
      <xs:element name="www-path" type="xs:string"/>
      <xs:element name="handlers" minOccurs="0">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="handler" type="tns:handler" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:element>

  <xs:complexType name="handler">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="description" type="xs:string"/>
      <xs:element name="context-root" type="xs:string"/>
      <xs:element name="file-path" type="xs:string"/>
      <xs:element name="init-params" minOccurs="0">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="init-param" type="tns:init-param" minOccurs="1" maxOccurs="unbounded" />
            </xs:sequence>
        </xs:complexType>
        </xs:element>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="init-param">
    <xs:sequence>
      <xs:element name="name" type="xs:string"/>
      <xs:element name="value" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

</xs:schema>

=== Letractively/sj-http-server/server/sj-http-server.xml
<server-conf xmlns="http://sj-http-server.googlecode.com/server"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://sj-http-server.googlecode.com/server ../etc/sj-http-server.xsd">
	<listen-interface>any</listen-interface>
        <listen-port>9090</listen-port>
        <www-path>../www/</www-path>
        <handlers>
		<handler>
			<name>Fortune Teller</name>
			<description>Presents a random Fortune Cookie Quote.</description>
			<context-root>fortune-cookie</context-root>
			<file-path>../fortune-teller/libfortune-teller.so</file-path>
		</handler>
		<handler>
			<name>Image Gallery</name>
			<description>Allows to view and upload images.</description>
			<context-root>image-gallery</context-root>
			<file-path>../image-gallery/libimage-gallery.so</file-path>
			<init-params>
				<init-param>
					<name>image.store.directory</name>
					<value>../work/image-gallery/</value>
				</init-param>
                                <init-param>
                                        <name>create.thumbnails</name>
                                        <value>false</value>
                                </init-param>
			</init-params>
		</handler>
	</handlers>
</server-conf>
